import { Registermodel } from "../server/auth";
import { Product } from "../server/productsType";
import Ro from "@/assets/2016-09-20_22-10-04.jpg";

export const createRegisterPayload = (phoneNumber: string, code:string): Registermodel=> ({
  ID:1,
  Name: "",
  Family: "",
  Mobilenumber: phoneNumber,
  Tel: "",
  Address: "",
  PostalCode: "",
  Code:code,
  Tokens :"",

});
export const cartItems: Product[] = [
  {
    id: 6,
    title: "ست ماگ کادویی وگل ۴۱۵۰-۵۹",
    price: 4545,
    quantity: 1,
    image: Ro.src,
    description: "",
    discountPercent: 0,
    discountPrice: 0,
    salePrice: 4545,
    stock: 10,
    unit: "عدد",
    category: "لوازم آشپزخانه",
    isAvailable: true,
  },
  {
    id: 1,
    title: "ست ماگ کادویی وگل ۴۱۵۰-۵۹",
    price: 4545,
    quantity: 1,
    image: Ro.src,
    description: "",
    discountPercent: 0,
    discountPrice: 0,
    salePrice: 4545,
    stock: 10,
    unit: "عدد",
    category: "لوازم آشپزخانه",
    isAvailable: true,
  },
  {
    id: 2,
    title: "ست ماگ کادویی وگل ۴۱۵۰-۵۹",
    price: 4545,
    quantity: 1,
    image: Ro.src,
    description: "",
    discountPercent: 0,
    discountPrice: 0,
    salePrice: 4545,
    stock: 10,
    unit: "عدد",
    category: "لوازم آشپزخانه",
    isAvailable: true,
  },
  {
    id: 3,
    title: "ست ماگ کادویی وگل ۴۱۵۰-۵۹",
    price: 4545,
    quantity: 1,
    image: Ro.src,
    description: "",
    discountPercent: 0,
    discountPrice: 0,
    salePrice: 4545,
    stock: 10,
    unit: "عدد",
    category: "لوازم آشپزخانه",
    isAvailable: true,
  },
  {
    id: 4,
    title: "ست ماگ کادویی وگل ۴۱۵۰-۵۹",
    price: 4545,
    quantity: 1,
    image: Ro.src,
    description: "",
    discountPercent: 0,
    discountPrice: 0,
    salePrice: 4545,
    stock: 10,
    unit: "عدد",
    category: "لوازم آشپزخانه",
    isAvailable: true,
  },
  {
    id: 5,
    title: "ست ماگ کادویی وگل ۴۱۵۰-۵۹",
    price: 4545,
    quantity: 1,
    image: Ro.src,
    description: "",
    discountPercent: 0,
    discountPrice: 0,
    salePrice: 4545,
    stock: 10,
    unit: "عدد",
    category: "لوازم آشپزخانه",
    isAvailable: true,
  },
];